### ISSUE TITLE
Diffuse map output blurry using default settings

### ISSUE THREAD

**Issue by GitGhillie** [pcwalton/gltf-ibl-sampler-egui#5]
I'm working with https://polyhaven.com/a/kloofendal_48d_partly_cloudy_puresky 1k exr and gltf-ibl-sampler-egui default settings, built with `cargo run --release`.
The resulting diffuse map looks like this:
![image](https://github.com/pcwalton/gltf-ibl-sampler-egui/assets/23659539/f1915c63-d373-46d3-99d5-7e18c42f5c56)
I don't see anything in the log/console except for:
```
warning: gltf-ibl-sampler-egui@0.1.0: Compiler family detection failed due to error: ToolExecError: Command "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX64\\x64\\cl.exe" "-E" "E:\\Assets\\gltf-ibl-sampler-egui\\target\\release\\build\\gltf-ibl-sampler-egui-d043a6558da621f4\\out\\10241310318780672477detect_compiler_family.c" with args C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\bin\HostX64\x64\cl.exe did not execute successfully (status code exit code: 2).
```
However, I don't think this is the issue since I'm getting something at least.

![image](https://github.com/pcwalton/gltf-ibl-sampler-egui/assets/23659539/21b56050-3ce2-4017-814e-e77ff5af6aec)

**Comment by pcwalton** [comment]
Have you validated against the normal [glTF IBL Sampler](https://github.com/KhronosGroup/glTF-IBL-Sampler)? At first glance this looks correct. The diffuse map is supposed to be extremely blurry.

**Comment by GitGhillie** [comment]
I see, looks like my expectations got confused somewhere along the way. Anyways thanks for making this!
